"use client";

import { useCallback, useState } from "react";
import { useChatStore } from "@/lib/stores/chat-store";




/**
 * Export the current chat conversation as PDF or Markdown.
 * PDF uses the browser's print-to-PDF capability.
 * Markdown generates a downloadable .md file.
 */
export function ChatExport() {
  const { messages, ragCitations } = useChatStore();
  const [exporting, setExporting] = useState(false);
  const [showMenu, setShowMenu] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  const showToast = (message: string) => {
    setToast(message);
    setTimeout(() => setToast(null), 2500);
  };

  // ── Markdown Export ─────────────────────────────────────────
  const exportToMarkdown = useCallback(() => {
    if (messages.length === 0) return;
    setExporting(true);
    setShowMenu(false);

    const dateStr = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
    const timeStr = new Date().toLocaleTimeString("en-IN", {
      hour: "2-digit",
      minute: "2-digit",
    });

    let md = `# 🗳️ ElectionGuide AI — Chat Export\n\n`;
    md += `**Date:** ${dateStr} at ${timeStr}  \n`;
    md += `**Messages:** ${messages.length} • **Sources:** ${ragCitations.length}\n\n`;
    md += `---\n\n`;

    messages.forEach((m) => {
      const time = new Date(m.createdAt).toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
      });
      if (m.role === "user") {
        md += `### 🧑 You (${time})\n\n${m.content}\n\n`;
      } else {
        md += `### 🤖 ElectionGuide AI (${time})\n\n${m.content}\n\n`;
      }
    });

    if (ragCitations.length > 0) {
      md += `---\n\n## 📚 Sources Cited\n\n`;
      ragCitations.forEach((c) => {
        const url = c.sourceUrl || `https://${c.domain || "eci.gov.in"}`;
        md += `${c.number}. **[${c.title}](${url})** — ${c.snippet}\n`;
      });
      md += `\n`;
    }

    md += `---\n\n`;
    md += `*Generated by ElectionGuide AI — Powered by Gemini Pro*  \n`;
    md += `*Disclaimer: Always verify voting information with your local election official's office or official ECI website (eci.gov.in)*\n`;

    // Download
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `electionguide-chat-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setExporting(false);
    showToast("Markdown exported ✓");
  }, [messages, ragCitations]);

  // ── PDF Export ──────────────────────────────────────────────
  const exportToPDF = useCallback(() => {
    if (messages.length === 0) return;
    setExporting(true);
    setShowMenu(false);

    // Build HTML document for print
    const citationsHtml = ragCitations
      .map(
        (c) => `
      <div style="padding:8px 12px;border:1px solid #ddd;border-radius:8px;margin-bottom:6px;">
        <div style="display:flex;align-items:center;gap:6px;margin-bottom:4px;">
          <span style="background:#1a237e;color:white;width:18px;height:18px;border-radius:4px;display:inline-flex;align-items:center;justify-content:center;font-size:10px;font-weight:700;">${c.number}</span>
          <strong style="font-size:12px;">${c.title}</strong>
        </div>
        <p style="font-size:11px;color:#666;margin:0;">${c.snippet}</p>
        ${c.sourceUrl ? `<a href="${c.sourceUrl}" style="font-size:10px;color:#1a237e;">${c.domain || c.sourceUrl}</a>` : ""}
      </div>`
      )
      .join("");

    const messagesHtml = messages
      .map((m) => {
        const isUser = m.role === "user";
        const bgColor = isUser ? "#1a237e" : "#f8f9ff";
        const textColor = isUser ? "#ffffff" : "#1a1a2e";
        const align = isUser ? "right" : "left";
        const label = isUser ? "You" : "ElectionGuide AI";
        const labelColor = isUser ? "#8c9eff" : "#1a237e";

        // Clean markdown for PDF
        const content = m.content
          .replace(/\*{1,2}([^*]+)\*{1,2}/g, "<strong>$1</strong>")
          .replace(/\n/g, "<br/>")
          .replace(/🍿/g, "🍿 ")
          .replace(/🥪/g, "🥪 ")
          .replace(/🍽️/g, "🍽️ ");

        return `
        <div style="text-align:${align};margin-bottom:16px;">
          <p style="font-size:10px;color:${labelColor};margin-bottom:4px;font-weight:600;">${label}</p>
          <div style="display:inline-block;max-width:80%;text-align:left;padding:12px 16px;border-radius:12px;background:${bgColor};color:${textColor};font-size:13px;line-height:1.6;border:${isUser ? "none" : "1px solid #e0e0e0"};">
            ${content}
          </div>
          <p style="font-size:9px;color:#999;margin-top:2px;">${new Date(m.createdAt).toLocaleTimeString()}</p>
        </div>`;
      })
      .join("");

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ElectionGuide AI — Chat Export</title>
  <style>
    @page { margin: 20mm; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1a1a2e; max-width: 700px; margin: 0 auto; }
    .header { text-align: center; padding: 20px 0 16px; border-bottom: 2px solid #1a237e; margin-bottom: 24px; }
    .header h1 { font-size: 20px; color: #1a237e; margin: 0 0 4px; }
    .header p { font-size: 11px; color: #666; margin: 0; }
    .footer { text-align: center; padding: 16px 0; border-top: 1px solid #eee; margin-top: 24px; font-size: 10px; color: #999; }
    .citations-section { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; }
    .citations-section h3 { font-size: 13px; color: #1a237e; margin-bottom: 8px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🗳️ ElectionGuide AI</h1>
    <p>Chat Export — ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })} at ${new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}</p>
    <p>${messages.length} messages • ${ragCitations.length} sources cited</p>
  </div>
  
  ${messagesHtml}

  ${
    ragCitations.length > 0
      ? `<div class="citations-section">
           <h3>📚 Sources Cited</h3>
           ${citationsHtml}
         </div>`
      : ""
  }

  <div class="footer">
    <p>Generated by ElectionGuide AI — Powered by Gemini Pro</p>
    <p>Disclaimer: Always verify voting information with your local election official's office or official ECI website (eci.gov.in)</p>
  </div>
</body>
</html>`;

    // Open in new window and trigger print
    const printWindow = window.open("", "_blank", "width=800,height=600");
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      // Wait for content to render before printing
      setTimeout(() => {
        printWindow.print();
        setExporting(false);
        showToast("PDF export ready ✓");
      }, 500);
    } else {
      // Fallback: download as HTML
      const blob = new Blob([html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `electionguide-chat-${Date.now()}.html`;
      a.click();
      URL.revokeObjectURL(url);
      setExporting(false);
      showToast("HTML exported ✓");
    }
  }, [messages, ragCitations]);

  if (messages.length === 0) return null;

  return (
    <div className="relative">
      {/* Export button */}
      <button
        onClick={() => setShowMenu(!showMenu)}
        disabled={exporting}
        className="p-1.5 text-outline hover:text-on-surface hover:bg-surface-container rounded transition-colors disabled:opacity-50"
        title="Export chat"
        aria-label="Export conversation"
        aria-expanded={showMenu}
      >
        <span className="material-symbols-outlined text-[18px]">
          {exporting ? "hourglass_top" : "download"}
        </span>
      </button>

      {/* Format selector dropdown */}
      {showMenu && (
        <>
          {/* Invisible backdrop to close menu */}
          <div
            className="fixed inset-0 z-40"
            onClick={() => setShowMenu(false)}
          />
          <div className="absolute bottom-full right-0 mb-1 bg-white border border-outline-variant rounded-xl shadow-lg overflow-hidden z-50 min-w-[160px] animate-in fade-in-0 zoom-in-95 duration-150">
            <button
              onClick={exportToPDF}
              className="w-full flex items-center gap-2.5 px-3 py-2.5 text-[13px] text-on-surface hover:bg-surface-container transition-colors"
            >
              <span className="material-symbols-outlined text-[18px] text-error">
                picture_as_pdf
              </span>
              Export as PDF
            </button>
            <button
              onClick={exportToMarkdown}
              className="w-full flex items-center gap-2.5 px-3 py-2.5 text-[13px] text-on-surface hover:bg-surface-container transition-colors border-t border-outline-variant"
            >
              <span className="material-symbols-outlined text-[18px] text-primary">
                description
              </span>
              Export as Markdown
            </button>
          </div>
        </>
      )}

      {/* Toast notification */}
      {toast && (
        <div className="fixed bottom-20 left-1/2 -translate-x-1/2 bg-inverse-surface text-inverse-on-surface text-[13px] font-medium px-4 py-2.5 rounded-xl shadow-lg z-[100] animate-in fade-in-0 slide-in-from-bottom-2 duration-200 flex items-center gap-2">
          <span className="material-symbols-outlined text-[16px] text-tertiary-fixed">
            check_circle
          </span>
          {toast}
        </div>
      )}
    </div>
  );
}
